# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: reservation-postgres
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: reservation-backend
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: reservation_db

  frontend:
    build: ./frontend
    container_name: reservation-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  postgres-data:
