'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React, { useState, useEffect } from 'react';

export const metadata: Metadata = {
  title: "My Reservation App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // نمونه‌ای از مدیریت دارک‌مود در سطح روت
  const [isDark, setIsDark] = useState(false);
  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [isDark]);

  return (
    <html lang="en">
        {/* اگر بخواهید dark mode را از اول روی HTML بگذارید، می‌توانید className="dark" اضافه کنید */}

      <body
        className="bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 transition-colors"
        >
        {/* دکمه‌ای برای تغییر تم به صورت ساده */}
        <button
          onClick={() => setIsDark(!isDark)}
          className="m-4 p-2 border rounded"
        >
          Toggle Dark Mode
        </button>

        {/* این children همان صفحاتی است که در لایه پایین‌تر قرار دارد (page.tsx ها) */}
        {children}
      </body>
    </html>
  );
}
